import type { Actions } from '@sveltejs/kit';
import type { PageServerLoad } from './$types';
import { Octokit } from 'octokit';

export const actions: Actions = {
	createRepo: async ({ cookies, locals }) => {
		const { user } = locals;
		console.log(user);
		if (!user) {
			return { message: 'You must be logged in to create a repo', data: null };
		}

		console.log('creating a repo');

		const githubToken = user.githubToken;

		const octokit = new Octokit({
			auth: githubToken
		});

		const resp = await octokit.rest.repos.createForAuthenticatedUser({
			name: 'test-repo',
			description: 'A test repository generated by ModBox',
			auto_init: true
		});

		return { data: resp.data };
	},
	listRepos: async ({ locals }) => {
		const { user } = locals;
		if (!user) {
			return { message: 'You must be logged in to list repos', data: null };
		}

		const githubToken = user.githubToken;

		const octokit = new Octokit({
			auth: githubToken
		});

		const repos = await octokit.rest.repos.listForAuthenticatedUser({
			type: 'owner'
		});

		console.log('Repos', repos);

		return { data: repos.data };
	}
};
